<% proxy_vars = {} %>
<% %w(http_proxy https_proxy no_proxy).each do |envvar| %>
<%   if ENV.key?(envvar) %>
<%     proxy_vars[envvar] = ENV[envvar] %>
<%   end %>
<% end %>
---
driver:
  name: vagrant

<% if proxy_vars.size > 0 %>
driver_config:
<% %w(http_proxy https_proxy no_proxy).each do |envvar| %>
<% if ENV.key?(envvar) %>
  <%= envvar %>: '<%= ENV[envvar] %>'
<% end %>
<% end %>

<% end %>

provisioner:
  name: chef_zero
<% if proxy_vars.size > 0 %>
  client_rb:
<% %w(http_proxy https_proxy no_proxy).each do |envvar| %>
<% if ENV.key?(envvar) %>
    <%= envvar %>: '<%= ENV[envvar] %>'
<% end %>
<% end %>

<% end %>

platforms:
  - name: win2012r2
    driver:
      box_url: https://mvnrepo.nordstrom.net/nexus/service/local/repositories/releases/content/com/nordstrom/vagrant/win2012r2-standard/1.0.4/win2012r2-standard-1.0.4.box
      gui: false

suites:
  - name: default
    run_list:
      - recipe[testsetup::default]
